### ISSUE TITLE
Faucet server

### ISSUE THREAD

**Issue by dakom** [Lay3rLabs/climb#31]
Not part of core functionality exported by `layer-climb`, rather a totally separate binary that _uses_ `layer-climb`

This should provide an API similar to [cosmjs facuet](https://github.com/cosmos/cosmjs/tree/main/packages/faucet) and has the same API endpoints (/credit and /status).

No need to support all the env args, can use a climb-friendly approach like the signer pool for efficiency

Will be integrated into layer-sdk (see https://github.com/Lay3rLabs/layer-sdk/issues/163 for more info)

**Comment by ethanfrey** [comment]
This should build on the climb pools api, easily allowing a "master account" to fund a number of "sub accounts", each of which is serving user requests (to allow concurrency). This is not absolutely required, but it is part of the design of the CosmJS version and comes more or less for free.

These are the env variables supported by CosmJS and if we support them in the climb version

* **FAUCET_CONCURRENCY**        Number of distributor accounts (size of pool). Defaults to 5. (can be hardcoded if easier)
* **FAUCET_PORT**               Port of the webserver. Defaults to 8000.
* _FAUCET_MEMO_             (optional)  Memo for send transactions. Defaults to unset.
* **FAUCET_GAS_PRICE**          Gas price for transactions. Defaults to "0.025ulay".
* ~~FAUCET_GAS_LIMIT~~          Use simulate (auto) for gas limit for send transactions
* **FAUCET_MNEMONIC**           Secret mnemonic that serves as the base secret for the faucet HD accounts
* ~~FAUCET_PATH_PATTERN~~      Defaults to climb standard derivation path ("m/44'/118'/0'/0/a" ?).
* **FAUCET_ADDRESS_PREFIX**     The bech32 address prefix. Defaults to "layer".
* ~~FAUCET_TOKENS~~            The token denom to be sent (just use the gas token)
* **FAUCET_CREDIT_AMOUNT** Send this amount of gas token to a user requesting it. Defaults to 1_000_000.
* ~~FAUCET_REFILL_FACTOR~~     (Use some reasonable default in the climb pool) Send factor times credit amount on refilling.
* ~~FAUCET_REFILL_THRESHOLD~~  (Use some reasonable default in the climb pool) Refill when balance gets below factor times credit amount
* _FAUCET_COOLDOWN_TIME_   (optional, later)   Time (in seconds) after which an address can request more tokens. Can be set to "0". Defaults to 24 hours if unset or an empty string. _(We don't need to track this yet, future issue)_
                           
**bold** means required, _italic_ is optional, ~~striked~~ is not needed at all (use some hardcoded value if you have similar parameter there in climb)

**Comment by ethanfrey** [comment]
The main purpose is `/status` is to debug and ensure there are tokens. You can see sample output (just keep the same format) via `curl https://faucet.layer-p.net/status`

Here `chainTokens` and `availableTokens` are both set to one item, the gas token. Balances again are just lists of one items which is the gas token.

The holder is the original faucet account (derivation 0 of the mnemonic). distributors are all the various pool accounts (derivation 1-N of the mnemonic).

Please keep this for compatibility (some frontend code uses it). If you want to make a simpler format and serve that on `/`, you are more than welcome to.

```json
{
  "status": "ok",
  "nodeUrl": "http://cometbft:26657",
  "chainId": "layer-permissionless-3",
  "chainTokens": [
    "uperm"
  ],
  "availableTokens": [
    "uperm"
  ],
  "holder": {
    "address": "layer1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmt53rug",
    "balance": [
      {
        "denom": "uperm",
        "amount": "3893979122"
      }
    ]
  },
  "distributors": [
    {
      "address": "layer10dyr9899g6t0pelew4nvf4j5c3jcgv0rwnkg3x",
      "balance": [
        {
          "denom": "uperm",
          "amount": "4000000000"
        }
      ]
    },
    {
      "address": "layer1xy4yqngt0nlkdcenxymg8tenrghmek4ntzd2ty",
      "balance": [
        {
          "denom": "uperm",
          "amount": "4000000000"
        }
      ]
    },
    {
      "address": "layer142u9fgcjdlycfcez3lw8x6x5h7rfjlnf8rc2n5",
      "balance": [
        {
          "denom": "uperm",
          "amount": "4000000000"
        }
      ]
    }
  ]
}
```

**Comment by ethanfrey** [comment]
Here is a sample of requesting tokens (please use your own address here):

```bash
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"denom":"uperm","address":"layer10dyr9899g6t0pelew4nvf4j5c3jcgv0rwnkg3x"}' \
  https://faucet.layer-p.net/credit
```

Success output looks like this (status 200):

```
ok
```

Error output looks like this (eg. status 405 for cooldown):

```
Too many request for the same address. Blocked to prevent draining. Please wait 86400 seconds and try it again!
```

I doubt anyone uses these messages, Please feel free to turn them into json (eg. `{"status": "ok"}` or  `{"status": "error", "message": "Too many requests"}`)

**Comment by dakom** [comment]
can the results for "distrubutors" be dynamic?

What I mean is - with climb, the max concurrent clients is simply an upper bound, they're not actually created until necessary (e.g. even with max concurrency of 100, if it never reaches that popularity, there may only have been like 3 clients created and re-used from the pool)

It would be much nicer to only show the distributors that have actually been created, rather than force it to create them up to max concurrency just for display purposes

**Comment by ethanfrey** [comment]
Oh, that is totally fine.
I would set a max of say 5, and if you only create as needed, totally cool. It will likely only show one there unless there is high load.
I like that idea actually.

**Comment by dakom** [comment]
completed
